'use strict';
(()=>{
 const $=id=>document.getElementById(id), all=s=>[...document.querySelectorAll(s)];
 const motors={};
 const motorId=m=>m;
 const saved={}; function ensure(id){if(!motors[id]){motors[id]={pos:0,vel:0,current:0,state:'待机'};saved[id]=[360,30,60,60,1200];}return motors[id];}ensure('1');ensure('2');
 const ids=['single-angle','single-speed','single-accel','single-decel','single-current'];
 let selected='1',mode='single',job=null,chart=null,elapsed=0,lastRender=0;
 const num=id=>$(id).value.trim()===''?NaN:Number($(id).value);
 const fmt=(n,d=1)=>Number.isFinite(n)?n.toFixed(d):'—';
 function log(kind,message){const row=document.createElement('div');row.className='log-entry';const time=new Date().toLocaleTimeString('zh-CN',{hour12:false});row.textContent=`${time}  ${kind}  ${message}`;$('event-log').prepend(row);while($('event-log').children.length>100)$('event-log').lastChild.remove();}
 function profile(delta,rpm,acc,dec,current){const distance=Math.abs(delta),a=acc*6,b=dec*6;let v=rpm*6;v=Math.min(v,Math.sqrt(2*distance/(1/a+1/b)));const ta=v/a,td=v/b,tc=Math.max(0,(distance-v*ta/2-v*td/2)/v);return {delta,distance,sign:Math.sign(delta),v,a,b,ta,tc,td,total:ta+tc+td,current};}
 function sample(p,t){t=Math.max(0,Math.min(t,p.total));let x,v;if(t>=p.total)return {x:p.delta,v:0};if(t<p.ta){v=p.a*t;x=.5*p.a*t*t;}else if(t<p.ta+p.tc){v=p.v;x=.5*p.v*p.ta+p.v*(t-p.ta);}else{const r=p.total-t;v=p.b*r;x=p.distance-.5*p.b*r*r;}return {x:x*p.sign,v:v*p.sign/6};}
 function valid(id,min,max){const n=num(id);return Number.isFinite(n)&&n>=min&&n<=max;}
 function plan(){if(!Number.isInteger(num('motor-address'))||!valid('motor-address',1,255))return {error:'目标 ID 需为 1–255 的整数（模拟范围）。'};if(mode==='single'){if(!valid(ids[0],-3600,3600)||num(ids[0])===0)return {error:'角度需在 ±3600° 内，且不为 0。'};if(!valid(ids[1],.1,120)||!valid(ids[2],.1,240)||!valid(ids[3],.1,240)||!valid(ids[4],100,5000))return {error:'检查速度、加減速度和限流范围。'};return {axes:{[selected]:profile(...ids.map(num))}};}
 if(!valid('sync-duration',.5,60))return {error:'共同时间需为 0.5–60 秒。'};if(!['a','b'].every(k=>valid('sync-id-'+k,1,255)&&Number.isInteger(num('sync-id-'+k)))||num('sync-id-a')===num('sync-id-b'))return {error:'填写两个不同的 CAN ID（1–255）。'};const T=num('sync-duration'),axes={};for(const suffix of ['a','b']){const m=String(num('sync-id-'+suffix));ensure(m);const delta=num('sync-angle-'+suffix),current=num('sync-current-'+suffix);if(!valid('sync-angle-'+suffix,-3600,3600)||delta===0||!valid('sync-current-'+suffix,100,5000))return {error:'两轴行程应非零且不超过 ±3600°，限流 100–5000 mA。'};const rpm=Math.abs(delta)/(.75*T)/6,acc=rpm/(T/4);$('sync-speed-'+suffix).textContent=fmt(rpm);$('sync-accel-'+suffix).textContent=fmt(acc);if(rpm>120||acc>240||rpm<.1||acc<.1)return {error:'该时长超出模拟器速度 / 加速度范围，请调整时间或行程。'};axes[m]=profile(delta,rpm,acc,acc,current);}return {axes};}
 function refresh(){const p=plan(),busy=!!job;$('single-validation').textContent=mode==='single'?(p.error||''):'';$('sync-validation').textContent=mode==='sync'?(p.error||''):'';$('single-start').disabled=busy||mode!=='single'||!!p.error;$('sync-start').disabled=busy||mode!=='sync'||!!p.error;$('global-stop').disabled=!busy;$('single-stop').disabled=!busy||!job?.axes[selected];all('.quick-angles button').forEach(e=>e.disabled=busy);all('input').forEach(e=>e.disabled=busy);
 if(!busy){if(mode==='single'&&!p.error){const q=p.axes[selected];$('single-duration').textContent=fmt(q.total,2)+' s';$('single-target').textContent=fmt(motors[selected].pos+q.delta)+'°';$('single-profile').textContent=q.tc>.001?'梯形':'三角形';}for(const m of ['a','b'])$('sync-target-'+m).textContent=fmt(ensure(String(num('sync-id-'+m))).pos+num('sync-angle-'+m))+'°';}
 $('single-state-chip').textContent=motors[selected].state;return p;}
 function render(){$('legend-id-a').textContent='ID '+(mode==='single'?selected:num('sync-id-a'));$('legend-id-b').textContent='ID '+num('sync-id-b');for(const m of ['A','B']){const actual=mode==='single'?selected:String(num('sync-id-'+(m==='A'?'a':'b'))),s=ensure(actual);document.querySelector(`[data-telemetry="${m}"]`).dataset.id='ID '+actual;all(`[data-position-for="${m}"],[data-telemetry-position="${m}"]`).forEach(e=>e.textContent=fmt(s.pos)+'°');all(`[data-state-for="${m}"],[data-telemetry-state="${m}"]`).forEach(e=>e.textContent=s.state);all(`[data-telemetry-speed="${m}"]`).forEach(e=>e.textContent=fmt(s.vel)+' RPM');all(`[data-telemetry-current="${m}"]`).forEach(e=>e.textContent=Math.round(s.current)+' mA');all(`[data-status-dot="${m}"]`).forEach(e=>e.style.background=s.state==='运行中'?'#2563eb':'#a1a1aa');}
 $('footer-clock').textContent=new Date().toLocaleTimeString('zh-CN');$('single-state-chip').textContent=motors[selected].state;}
 function start(){if(job)return;const p=refresh();if(p.error)return;for(const [m,q] of Object.entries(p.axes)){q.origin=motors[m].pos;motors[m].state='运行中';log('预装',`ID ${motorId(m)} 相对 ${q.delta}° · ${fmt(q.v/6)} RPM · ${fmt(q.a/6)} RPM/s${mode==='sync'?' · 等待同步':''}`);}job={axes:p.axes,start:performance.now(),total:Math.max(...Object.values(p.axes).map(q=>q.total)),mode};chart=job;elapsed=0;log(mode==='sync'?'同步触发':'启动',mode==='sync'?'模拟 CAN 广播 FF 66，ID '+Object.keys(p.axes).join(' / ID ')+' 使用同一时钟':'ID '+motorId(selected)+' 开始试动');$('overall-state').textContent='运行中';$('chart-empty').style.display='none';refresh();}
 function tick(now){if(job){elapsed=Math.min((now-job.start)/1000,job.total);for(const [m,q] of Object.entries(job.axes)){const s=sample(q,elapsed);motors[m].pos=q.origin+s.x;motors[m].vel=s.v;motors[m].current=elapsed<q.total?Math.min(q.current,q.current*(.18+.52*Math.abs(s.v)/(q.v/6))):0;}
 $('overall-progress').style.width=100*elapsed/job.total+'%';if(elapsed>=job.total){const names=Object.keys(job.axes);names.forEach(m=>motors[m].state='已到位');log('完成',names.map(m=>`ID ${motorId(m)}: ${fmt(motors[m].pos)}°`).join(' · '));$('overall-state').textContent='已到位 · '+fmt(job.total,2)+' s';job=null;refresh();}}
 if(now-lastRender>40){render();draw();lastRender=now;}requestAnimationFrame(tick);}
 function stop(){if(!job)return;for(const m of Object.keys(job.axes)){motors[m].vel=0;motors[m].current=0;motors[m].state='已停止';}job=null;$('overall-state').textContent='已停止 · 保留当前位置';log('停止','取消本次运动，保持模拟位置');refresh();render();}
 function select(m){if(job)return;saved[selected]=ids.map(num);ensure(m);selected=m;chart=null;elapsed=0;$('chart-empty').style.display='';ids.forEach((id,i)=>$(id).value=saved[m][i]);document.body.dataset.selected='A';all('[data-motor]').forEach(e=>{e.classList.toggle('is-selected',e.dataset.motor===m);e.setAttribute('aria-pressed',e.dataset.motor===m);});$('single-motor-name').textContent=motorId(m);$('single-start-name').textContent=motorId(m);$('selected-motor-label').textContent='ID '+motorId(m);refresh();render();}
 function setMode(m){mode=m;document.body.dataset.mode=m;for(const name of ['single','sync']){$(name+'-panel').classList.toggle('is-hidden',name!==m);$('mode-'+name).classList.toggle('is-active',name===m);$('mode-'+name).setAttribute('aria-selected',name===m);}refresh();}
 function draw(){const c=$('trajectory-chart'),box=c.parentElement.getBoundingClientRect(),dpr=devicePixelRatio||1,w=Math.max(200,box.width),h=Math.max(180,box.height);if(c.width!==Math.round(w*dpr)||c.height!==Math.round(h*dpr)){c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);}const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const L=54,R=w-20,T=26,B=h-36;const values=chart?Object.values(chart.axes).map(q=>q.delta):[360];let lo=Math.min(0,...values),hi=Math.max(0,...values);if(hi===lo)hi=lo+1;const pad=(hi-lo)*.1;lo-=pad;hi+=pad;const total=chart?.total||4,X=t=>L+(R-L)*t/total,Y=v=>B-(B-T)*(v-lo)/(hi-lo);ctx.font='12px "Segoe UI", "Microsoft YaHei UI", sans-serif';ctx.textAlign='right';for(let i=0;i<=4;i++){const y=T+(B-T)*i/4;ctx.strokeStyle='#e9edf2';ctx.beginPath();ctx.moveTo(L,y);ctx.lineTo(R,y);ctx.stroke();ctx.fillStyle='#7b8493';ctx.fillText(Math.round(hi-(hi-lo)*i/4)+'°',L-9,y+4);}ctx.textAlign='center';for(let i=0;i<=4;i++)ctx.fillText(fmt(total*i/4,1)+'s',X(total*i/4),h-12);
 if(!chart)return;for(const [m,q] of Object.entries(chart.axes)){const color=m===Object.keys(chart.axes)[0]?'#2563eb':'#a855f7';for(const planned of [true,false]){ctx.strokeStyle=color;ctx.globalAlpha=planned?.23:1;ctx.lineWidth=planned?1.5:2.5;ctx.setLineDash(planned?[4,4]:[]);ctx.beginPath();const end=planned?total:elapsed;for(let i=0;i<=120;i++){const t=end*i/120,x=X(t),y=Y(sample(q,t).x);i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();}ctx.globalAlpha=1;ctx.setLineDash([]);ctx.fillStyle=color;ctx.beginPath();ctx.arc(X(elapsed),Y(sample(q,elapsed).x),4,0,Math.PI*2);ctx.fill();}$('chart-range').textContent='虚线：计划 · 实线：模拟反馈';}
 all('[data-motor]').forEach(e=>e.addEventListener('click',()=>select(e.dataset.motor)));for(const m of ['single','sync'])$('mode-'+m).addEventListener('click',()=>setMode(m));all('input').forEach(e=>e.addEventListener('input',refresh));$('single-start').addEventListener('click',start);$('sync-start').addEventListener('click',start);$('single-stop').addEventListener('click',stop);$('global-stop').addEventListener('click',stop);$('clear-log').addEventListener('click',()=>{$('event-log').replaceChildren();});$('reset-simulation').addEventListener('click',()=>{job=null;chart=null;elapsed=0;for(const m of Object.keys(motors))Object.assign(motors[m],{pos:0,vel:0,current:0,state:'待机'});$('overall-state').textContent='待机 · 等待指令';$('overall-progress').style.width='0%';$('chart-empty').style.display='';log('重置','两轴模拟位置归零');refresh();render();});
 $('motor-address').addEventListener('input',()=>{if(valid('motor-address',1,255)&&Number.isInteger(num('motor-address')))select(String(num('motor-address')));else refresh();});log('就绪','纯浏览器模拟，无真实 CAN 连接');refresh();render();requestAnimationFrame(tick);
})();