#pragma once
#define BABYTECH_OTA_BOARD "device-controller"
#define BABYTECH_OTA_HARDWARE "esp32-s3-n16r8"
#define BABYTECH_OTA_VERSION "0.1.0-ota1"
#define BABYTECH_OTA_BUILD 1
#define BABYTECH_OTA_STR_INNER(x) #x
#define BABYTECH_OTA_STR(x) BABYTECH_OTA_STR_INNER(x)
#define BABYTECH_OTA_IMAGE_ID "BABYTECH-OTA-IMAGE-V1|" BABYTECH_OTA_BOARD "|" \
    BABYTECH_OTA_HARDWARE "|" BABYTECH_OTA_STR(BABYTECH_OTA_BUILD) "|" BABYTECH_OTA_VERSION
