#pragma once

// Device-controller UART peer values. Keep the legacy names for existing builds.
#define DEVICE_UART_PEER_MAIN 1
#define DEVICE_UART_PEER_DISPLAY 2
#define MOTION_UART_PEER_BRAIN DEVICE_UART_PEER_MAIN
#define MOTION_UART_PEER_DISPLAY DEVICE_UART_PEER_DISPLAY

#if defined(DEVICE_UART_PEER) && defined(MOTION_UART_PEER) && \
    DEVICE_UART_PEER != MOTION_UART_PEER
#error "DEVICE_UART_PEER and MOTION_UART_PEER select different UART peers"
#endif

#ifndef DEVICE_UART_PEER
#ifdef MOTION_UART_PEER
#define DEVICE_UART_PEER MOTION_UART_PEER
#else
#define DEVICE_UART_PEER DEVICE_UART_PEER_DISPLAY
#endif
#endif

#ifndef MOTION_UART_PEER
#define MOTION_UART_PEER DEVICE_UART_PEER
#endif

#if DEVICE_UART_PEER != DEVICE_UART_PEER_MAIN && \
    DEVICE_UART_PEER != DEVICE_UART_PEER_DISPLAY
#error "DEVICE_UART_PEER must be MAIN (1) or DISPLAY (2)"
#endif
