#pragma once
#define MOTION_UART_PEER_BRAIN 1
#define MOTION_UART_PEER_DISPLAY 2
#define MOTION_UART_PEER_PRODUCT_BRAIN 4
#ifndef MOTION_UART_PEER
#define MOTION_UART_PEER MOTION_UART_PEER_DISPLAY
#endif
#define MOTION_HAS_PRODUCT (MOTION_UART_PEER == MOTION_UART_PEER_DISPLAY || MOTION_UART_PEER == MOTION_UART_PEER_PRODUCT_BRAIN)
#if MOTION_UART_PEER != MOTION_UART_PEER_BRAIN && !MOTION_HAS_PRODUCT
#error "MOTION_UART_PEER must be legacy BRAIN (1), DISPLAY (2), or product BRAIN (4)"
#endif
