#pragma once
#define MOTION_UART_PEER_BRAIN 1
#define MOTION_UART_PEER_DISPLAY 2
#ifndef MOTION_UART_PEER
#define MOTION_UART_PEER MOTION_UART_PEER_BRAIN
#endif
#if MOTION_UART_PEER != MOTION_UART_PEER_BRAIN && MOTION_UART_PEER != MOTION_UART_PEER_DISPLAY
#error "MOTION_UART_PEER must be BRAIN (1) or DISPLAY (2)"
#endif
