import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const require = createRequire(import.meta.url);
const { chromium } = require('C:/Users/xusen/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser = await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page = await browser.newPage({viewport:{width:1513,height:1039},deviceScaleFactor:1});
const errors=[]; const checks=[];
page.on('pageerror',e=>errors.push(e.message));
await fs.mkdir('qa',{recursive:true});
try {
 await page.goto('http://127.0.0.1:4175/',{waitUntil:'networkidle'});
 await page.getByRole('button',{name:'发送指令',exact:true}).waitFor();
 assert.match(await page.locator('body').innerText(),/01 F3 AB 01 00 6B/);
 checks.push('Initial F3 logical command and UI render');
 await page.screenshot({path:'qa/desktop.png',fullPage:true});
 await page.getByRole('button',{name:'发送指令',exact:true}).click();
 await page.waitForTimeout(600);
 assert.match(await page.locator('body').innerText(),/F3 02 6B/);
 checks.push('Send enable command and receive simulated ACK');
 await page.getByRole('tab',{name:'原始 HEX',exact:true}).click();
 await page.locator('#raw-command').fill('01 F3 AB 01 00 00');
 assert.equal(await page.getByRole('button',{name:'发送指令',exact:true}).isDisabled(),true);
 checks.push('Invalid checksum blocks send');
 await page.locator('#raw-command').fill('01 F3 AB 02 00 6B');
 assert.equal(await page.getByRole('button',{name:'发送指令',exact:true}).isDisabled(),true);
 checks.push('Known opcode with invalid field blocks send');
 await page.reload();
 const search=page.getByRole('searchbox',{name:'搜索指令名称或功能码'});
 await search.fill('CD');
 await page.locator('.library__item').filter({hasText:'梯形位置'}).click();
 const limit=page.getByRole('radio',{name:/CD/});
 if(await limit.count()) await limit.click();
 assert.match(await page.locator('body').innerText(),/Packet 2/);
 checks.push('Position variant encodes multiple CAN packets');
 await page.screenshot({path:'qa/position-command.png',fullPage:true});
 await page.reload();
 await page.locator('#can-address').fill('0');
 assert.equal(await page.getByRole('button',{name:'发送指令',exact:true}).isDisabled(),true);
 await page.locator('#can-address').fill('2');
 assert.match(await page.locator('body').innerText(),/未使能|失能/);
 await page.locator('#can-address').fill('1');
 checks.push('Invalid motor ID blocked and motor states independent');
 await page.getByRole('tab',{name:'常规试动',exact:true}).click();
 await page.locator('#manual-angle').fill('3600');
 await page.getByRole('button',{name:'发送运动指令',exact:true}).click();
 await page.waitForTimeout(450);
 await page.getByRole('button',{name:'全部停止',exact:true}).click();
 await page.waitForTimeout(400);
 const positionAfter=await page.locator('.metrics').innerText();
 await page.waitForTimeout(1400);
 const positionLater=await page.locator('.metrics').innerText();
 assert.equal(positionLater,positionAfter);
 checks.push('Global stop cancels motion with no delayed feedback');
 await page.screenshot({path:'qa/manual.png',fullPage:true});
 await page.reload();
 await page.setViewportSize({width:1280,height:800});
 await page.screenshot({path:'qa/desktop-1280.png',fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 assert.equal(overflow,false);
 assert.equal(await page.getByRole('button',{name:'全部停止',exact:true}).isVisible(),true);
 checks.push('1280x800 desktop: no horizontal overflow, stop accessible');
 assert.deepEqual(errors,[]);
 checks.push('No uncaught browser errors');
} finally {
 await fs.writeFile('qa/smoke-results.json',JSON.stringify({checks,errors},null,2));
 console.log(JSON.stringify({checks,errors},null,2));
 await browser.close();
}

